# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :
#Setting UP DC vagrant/ansible

require 'yaml'


current_dir    = File.dirname(File.expand_path(__FILE__))
configs        = YAML.load_file("#{current_dir}/../../VarFileConfig.yaml")
vagrant_config = configs['configs'][configs['configs']['w2016DC']]
#vagrant_config = configs['configs'][configs['configs']['use']]


Vagrant.configure("2") do |config|

  #Domain Controller section
  config.vm.define "windows2016-domain-controller" do |w2016DC|
    w2016DC.vm.box = "detectionlab/win2016" #TODO change the base image.
    w2016DC.vm.hostname = "dc"
    w2016DC.vm.boot_timeout = 600
    w2016DC.winrm.transport = :plaintext
    w2016DC.vm.communicator = "winrm"
    w2016DC.winrm.basic_auth_only = true
    w2016DC.winrm.timeout = 300
    w2016DC.winrm.retry_limit = 20
    #w2016DC.vm.network "forwarded_port", guest: 5985, host: 6000
    w2016DC.vm.network :private_network, ip: "192.168.38.102", gateway: "192.168.38.1", dns: "8.8.8.8"
    #w2016DC.vm.network :private_network, ip: "{{ windows_domain_controller_private_ip }}"
    w2016DC.vm.network "public_network"
    
    w2016DC.vm.provision "ansible" do |ansible|
      ansible.extra_vars = {
        ansible_port: 6000,
        win_password: '{{ win_password }}',
        }
        ansible.playbook = "../../ansible/playbooks/windows_dc.yml"
        ansible.config_file = "../../ansible/ansible.cfg"
        ansible.compatibility_mode = "2.0"
    end
  end
end
